packages:
  # Product apps and recursively nested app packages
  - apps/**

  # Shared packages and recursively nested packages
  - packages/**

allowBuilds:
  esbuild: true
  sharp: true

overrides:
  nextra-theme-docs>zod: 4.3.6
  nextra>zod: 4.3.6
