packages:
  # Product apps and recursively nested app packages
  - apps/**

  # Shared packages and recursively nested packages
  - packages/**

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - esbuild@0.28.1

overrides:
  esbuild: 0.28.1

patchedDependencies:
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
