export {
	CONFIG_FILE_NAME,
	ConfigError,
	type ConfigErrorCode,
	DATA_DIRECTORY_NAME,
	DOCUMENT_DIRECTORY_NAMES,
	defineConfig,
	discoverRepository,
	documentKindDirectory,
	entityGeneratedDirectory,
	GENERATED_DIRECTORY_NAME,
	LEGACY_GENERATED_DIRECTORY_NAME,
	loadRepository,
	REPOSITORY_ROOT_MARKERS,
	type Repository,
	RepositoryDirectorySchema,
	RepositorySchema,
	type ResolvedConfig,
	type ResolvedTaskDefaults,
	resolveInitializationRoot,
	SNAPSHOTS_DIRECTORY_NAME,
	TASKS_DIRECTORY_NAME,
} from './config/config.ts'
export {
	type DoctorResult,
	diagnoseRepository,
	type RepositoryDiagnostic,
	type RepositoryDiagnosticCode,
} from './diagnostics/doctor.ts'
export {
	type CreateDocumentInput,
	CreateDocumentInputSchema,
	type CreateDocumentOptions,
	CreateDocumentOptionsSchema,
	createDocument,
	type DeleteDocumentOptions,
	DeleteDocumentOptionsSchema,
	type DocumentBatchOperation,
	type DocumentBatchOptions,
	type DocumentBatchProgress,
	type DocumentBatchResult,
	type DocumentIdMigration,
	type DocumentIdMigrationOptions,
	type DocumentIdMigrationProgress,
	type DocumentRecord,
	DocumentRepositoryError,
	type DocumentRepositoryErrorCode,
	deleteDocument,
	documentTemplate,
	executeDocumentBatch,
	exportDocument,
	type ImportDocumentOptions,
	importDocument,
	listDocuments,
	migrateDocumentIds,
	normalizeDocumentKind,
	parseDocumentFile,
	readDocument,
	serializeDocumentFile,
	slugifyDocumentTitle,
	type UpdateDocumentInput,
	UpdateDocumentInputSchema,
	type UpdateDocumentOptions,
	UpdateDocumentOptionsSchema,
	updateDocument,
} from './documents/documentRepository.ts'
export {
	type GeneratedViewsResult,
	type GenerateViewsOptions,
	GenerateViewsOptionsSchema,
	generateViews,
} from './generated/generatedViews.ts'
export {
	buildDocumentGraph,
	type DerivedDocumentRelationships,
	DocumentGraph,
	type DocumentGraphDiagnostic,
	type DocumentGraphDiagnosticCode,
	DocumentGraphError,
	inspectDocumentGraph,
} from './graph/documentGraph.ts'
export {
	buildTaskGraph,
	type DerivedTaskRelationships,
	inspectTaskGraph,
	TaskGraph,
	type TaskGraphDiagnostic,
	type TaskGraphDiagnosticCode,
	TaskGraphError,
	TaskRecordSchema,
	TaskRecordsSchema,
} from './graph/taskGraph.ts'
export {
	assertEntityFileNameMatchesId,
	buildEntityFileName,
	ENTITY_ID_LENGTH,
	type EntityFileNameParts,
	extractSequenceFromEntityId,
	extractSequenceFromFileName,
	generateEntityId,
	nextEntitySequence,
	parseEntityFileName,
	planEntitySequences,
	resolveEntityFileName,
	slugifyTitle,
} from './ids/entityId.ts'
export {
	type BuildTaskIndexOptions,
	BuildTaskIndexOptionsSchema,
	buildTaskIndex,
	TaskIndex,
} from './indexing/taskIndex.ts'
export {
	normalizeRepositoryPath,
	RepositoryPathError,
	type RepositoryPathErrorCode,
	RepositoryRelativePathSchema,
	repositoryPathsRelate,
} from './projects/repositoryPath.ts'
export {
	applyFileTransaction,
	FileTransactionError,
	type FileTransactionErrorCode,
	type FileTransactionOperation,
	FileTransactionOperationSchema,
} from './repository/fileTransaction.ts'
export {
	DEFAULT_DATA_IGNORE_SOURCE,
	type InitializeRepositoryOptions,
	initializeRepository,
} from './repository/repository.ts'
export {
	DOCUMENT_SORT_DIRECTIONS,
	DOCUMENT_SORT_KEYS,
	type DocumentQuery,
	type DocumentQueryResult,
	DocumentQuerySchema,
	type DocumentSortDirection,
	type DocumentSortKey,
	queryDocumentRecords,
	queryDocuments,
} from './search/documentQuery.ts'
export {
	queryTaskRecords,
	queryTasks,
	TASK_SORT_DIRECTIONS,
	TASK_SORT_KEYS,
	type TaskQuery,
	type TaskQueryResult,
	TaskQuerySchema,
	type TaskSortDirection,
	type TaskSortKey,
} from './search/taskQuery.ts'
export {
	type CreateSnapshotOptions,
	CreateSnapshotOptionsSchema,
	createSnapshot,
	listSnapshots,
	type RestoreSnapshotOptions,
	RestoreSnapshotOptionsSchema,
	type RestoreSnapshotResult,
	restoreSnapshot,
	type SnapshotChange,
	type SnapshotFile,
	type SnapshotManifest,
} from './snapshots/snapshotRepository.ts'
export {
	type RepositorySyncOptions,
	type RepositorySyncProgress,
	type RepositorySyncResult,
	syncRepository,
} from './sync/repositorySync.ts'
export {
	applySynchronization,
	type PlanSynchronizationOptions,
	PlanSynchronizationOptionsSchema,
	planSynchronization,
	SynchronizationError,
	type SynchronizationErrorCode,
} from './sync/synchronization.ts'
export {
	type ParseTaskFileOptions,
	ParseTaskFileOptionsSchema,
	parseTaskFile,
	serializeTaskFile,
	TaskFileError,
	type TaskFileErrorCode,
	type TaskFileIssue,
} from './tasks/taskFile.ts'
export {
	type CoreWarning,
	type CreateTaskInput,
	CreateTaskInputSchema,
	type CreateTaskOptions,
	CreateTaskOptionsSchema,
	createTask,
	type DeleteTaskOptions,
	DeleteTaskOptionsSchema,
	deleteTask,
	generateTaskId,
	listTasks,
	migrateTaskIds,
	readTask,
	type TaskIdMigration,
	type TaskIdMigrationOptions,
	type TaskIdMigrationProgress,
	type TaskRecord,
	TaskRepositoryError,
	type TaskRepositoryErrorCode,
	type UpdateTaskInput,
	UpdateTaskInputSchema,
	type UpdateTaskOptions,
	UpdateTaskOptionsSchema,
	updateTask,
} from './tasks/taskRepository.ts'
export {
	CoreValidationError,
	type CoreValidationIssue,
} from './validation/coreValidation.ts'
